executor: slurm
use-conda: True
jobs: 50 # Have up to N jobs submitted at any given time
latency-wait: 30 # Wait N seconds for output files due to latency
retries: 2 # Retry jobs N times.
max-jobs-per-second: 5
max-status-checks-per-second: 5


# These resources will be applied to all rules. Can be overriden on a per-rule basis below.
default-resources:
  mem_mb: attempt * 16000
  slurm_partition: "short"
  runtime: 60 # In mutes

set-threads:
  bwa_mem: 32

